---
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py3-plus]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.17"
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
      - id: no-commit-to-branch
      - id: trailing-whitespace
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "3.6.1"
    hooks:
      - id: editorconfig-checker
        alias: ec
        exclude: uv\.lock
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
      - id: pylint
        name: pylint
        entry: uv run pylint
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
