---
# yamllint disable rule:line-length
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# yamllint enable rule:line-length
name: PR Lint

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

permissions: read-all

env:
  TRIVY_SEVERITY: CRITICAL,HIGH
  DISABLE_LINTERS: GO_GOLANGCI_LINT

jobs:
  Linter:
    name: PR Lint
    runs-on: ubuntu-latest
    permissions:
      contents: write  # only for delete-branch option
      issues: write
      pull-requests: write
      statuses: write

    steps:
      # yamllint disable rule:line-length
      - uses: ivuorinen/actions/pr-lint@459781a253d1c53960506b124ae3beaa1090e2a3  # v2026.03.22
      # yamllint enable rule:line-length
