---
# yamllint disable rule:line-length
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# yamllint enable rule:line-length
name: PR Lint

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

permissions: read-all

env:
  TRIVY_SEVERITY: CRITICAL,HIGH
  DISABLE_LINTERS: GO_GOLANGCI_LINT

jobs:
  Linter:
    name: PR Lint
    runs-on: ubuntu-latest
    permissions:
      contents: write # only for delete-branch option
      issues: write
      pull-requests: write
      statuses: write

    steps:
      # yamllint disable rule:line-length
      - uses: ivuorinen/actions/pr-lint@877acc6d8b013051a6acf83c0e876d3a2b46210a # v2026.06.08
        with:
          token: ${{ github.token }}
      # yamllint enable rule:line-length
