---
name: Python tests

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # yamllint disable-line rule:line-length
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install uv
        # yamllint disable-line rule:line-length
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        shell: bash
        run: uv sync --all-groups

      - name: Run Ruff linting
        shell: bash
        run: uv run ruff check .

      - name: Run tests with coverage
        shell: bash
        run: |
          uv run pytest --cov=aeonview --cov-report=term-missing
