---
name: Python tests

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # yamllint disable-line rule:line-length
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Install uv
        # yamllint disable-line rule:line-length
        uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb  # v5.4.1

      - name: Install dependencies
        shell: bash
        run: uv sync --all-groups

      - name: Run Ruff linting
        shell: bash
        run: uv run ruff check .

      - name: Run tests with coverage
        shell: bash
        run: |
          uv run pytest --cov=aeonview --cov-report=term-missing
