---
name: Python tests

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # yamllint disable-line rule:line-length
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install uv
        # yamllint disable-line rule:line-length
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57  # v8.0.0
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        shell: bash
        run: uv sync --all-groups

      - name: Run Ruff linting
        shell: bash
        run: uv run ruff check .

      - name: Run tests with coverage
        shell: bash
        run: |
          uv run pytest --cov=aeonview --cov-report=term-missing
